### ISSUE TITLE
Problem with pyvcf 

### ISSUE THREAD

**Issue by RichardUABC** [dmnfarrell/snpgenie#2]
Hi
I have a problem when run the command for installation:

pip install -e git+https://github.com/dmnfarrell/snipgenie.git#egg=snipgenie

This is what is displayed in the console: ( I have ubuntu 20.04 and python 3.8)

ERROR: Could not find a version that satisfies the requirement pyvcf>=0.6 (from snipgenie) (from versions: 0.6.8.linux-x86_64, 0.0.0, 0.1, 0.2, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8)
ERROR: No matching distribution found for pyvcf>=0.6

How can I complete the installation?

**Comment by dmnfarrell** [comment]
I think this was a bug in setup.py. You can try again.

**Comment by dmnfarrell** [comment]
Dependency has been changed to pyvcf3 which is a drop in replacement for the older pyvcf package.
