### ISSUE TITLE
[Feature Request] Use -1 and -2 arguments for reads

### ISSUE THREAD

**Issue by jolespin** [dmnfarrell/snpgenie#3]
It would be very convenient to use the -1 and -2 arguments like spades (or --R1 and --R2 like snippy) for inputting reads.

**Comment by dmnfarrell** [comment]
Hi. The tool is really to run files in batches so individual files are not provided at the command line. Only folder names are given.

**Comment by jolespin** [comment]
I am running in batches but my directory structure is different so I need to relabel everything.  What about a manifest table option for input like with QIIME2? 

[id_sample]<tab>[path/to/read_1]<tab>[path/to/read_2]

This will provide much more flexibility.

**Comment by dmnfarrell** [comment]
I guess you checked that you're using the right separator. Can you give me an example of your directory, filename structure to test. Otherwise the manifest table might be a good idea.

**Comment by jolespin** [comment]
Here's an example of the directory structure I use: 

```
(base) [jespinoz@login01 TestVEBA]$ ls veba_output/preprocess/*/output/* | grep "cleaned" | head -n 10
veba_output/preprocess/S1/output/cleaned_1.fastq.gz
veba_output/preprocess/S1/output/cleaned_2.fastq.gz
veba_output/preprocess/S2/output/cleaned_1.fastq.gz
veba_output/preprocess/S2/output/cleaned_2.fastq.gz
veba_output/preprocess/S3/output/cleaned_1.fastq.gz
veba_output/preprocess/S3/output/cleaned_2.fastq.gz
veba_output/preprocess/S4/output/cleaned_1.fastq.gz
veba_output/preprocess/S4/output/cleaned_2.fastq.gz
```

Samples are S1, S2, S3, and S4

Makes wildcard operations much easier.

**Comment by dmnfarrell** [comment]
Yes this won't work because it derives sample names from the file and they have to be unique. It would need the sample table to be explicitly provided as you said.

**Comment by dmnfarrell** [comment]
You can now provide a manifest file using the -M switch or 'manifest' key in the config file
Use this format. The sample name must be unique obviously.
```
sample,filename1,filename2
S1,/test_folder/S1/cleaned_1.fastq.gz,/test_folder/S1/cleaned_2.fastq.gz
S2,/test_folder/S2/cleaned_1.fastq.gz,/test_folder/S2/cleaned_2.fastq.gz
S3,/test_folder/S3/cleaned_1.fastq.gz,/test_folder/S3/cleaned_2.fastq.gz
```

**Comment by jolespin** [comment]
What's the best way to update Snipgenie to use this functionality?

**Comment by dmnfarrell** [comment]
Just run the install command again. 
`pip install -e git+https://github.com/dmnfarrell/snipgenie.git#egg=snipgenie`
